### PR TITLE
add landingPage

### PR DESCRIPTION
**Pull request by Varu98**

### CODE REVIEW

**Review by techieshubham30 — APPROVED** [review]
Everything looks good.

**Review by manojasarsa — APPROVED** [review]
Looks amazing!! Just a small suggestion, if you can increase the font-size little bit more, it would look great!

**Comment by Varu98** [comment]
> Looks amazing!! Just a small suggestion, if you can increase the font-size little bit more, it would look great!

Awesome! will do Thanks!! 😄

**Comment by preethasri** [comment]
Ui looking colorful vardan👍

**Comment by Varu98** [comment]
> 

Thanks!! 😄

**Pull request merged**
